### ISSUE TITLE
Entering A New Encryption Password

### ISSUE THREAD

**Issue by tox-m67** [funilrys/PKGBUILD#11]
Good Morning All,

I've used the Laverna desktop app in the past but have since forgotten my old encryption password. I'm not really concerned about trying to retrieve the information, however I would like to use Laverna again. However whenever I try to reinstall the desktop app the setup process just immediately asks for my old encryption password. I've tried uninstalling and reinstalling the software, but no joy. If anyone could help it would be greatly appreciated.

**Comment by funilrys** [comment]
Hi @tox-m67 

Unfortunately this issue will never be fixed.

Please report to https://github.com/Laverna/laverna/issues/971#issuecomment-411423965 for the current state of Laverna (deprecated) and https://github.com/encryptic-team/encryptic for the future of Laverna.

Have a nice day/night.

Cheers,
Nissar

**Comment by tox-m67** [comment]
Hi Nissar,

Thanks for letting me know this. I'm still new to the world of Guthub and encryption in general. I've been looking for a reliable note taking app since Evernote threw me overboard. I'll definitely give Encryptic a look. Thank you.

**Comment by funilrys** [comment]
Welcome on GitHub!!! 

You're welcome! Hope that you'll enjoy Encryptic along with the Open Source world!

Cheers,
Nissar
